; Generated by scripts/generate-agent-discovery.mjs. Do not edit by hand.
!define PLVS_AGENT_PRODUCT_NAME "PLVS"
!define PLVS_AGENT_IDENTIFIER "com.soundoer.plvs"
!define PLVS_AGENT_VERSION "0.11.0"
!define PLVS_AGENT_REG_KEY "Software\SounDoer\PLVS"
